apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-app
  namespace: {{ .Values.installation.name }}
  labels: 
    component: core-app

spec:
  selector:
    matchLabels:
      component: core-app
  replicas: 1
  template:
    metadata:
      labels:
        component: core-app
    spec:
      containers:
        - name: core-app
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          volumeMounts:
          - name: init-pvc
            mountPath: /app/config/initializers/custom
          ports:
          - containerPort: 80
          envFrom:
          - configMapRef:
              name: core-env
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: core-ap.postgres.credentials.postgresql.acid.zalan.do
                  key: password
          resources:
            requests:
              memory: 1536Mi
            limits:
              memory: 1536Mi
      imagePullSecrets:
      - name: regcred
      volumes:
        - name: init-pvc
          persistentVolumeClaim:
            claimName: init-pvc