apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-sneakers
  namespace: {{ .Values.installation.name }}
  labels: 
    component: core-sneakers
spec:
  selector:
    matchLabels:
      component: core-sneakers
  template:
    metadata:
      labels:
        component: core-sneakers   
    spec:
      containers:
        - name: core-sneakers
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
          - containerPort: 80
          command: ["bin/rails"]
          args: ["sneakers:run"]
          # securityContext:
          #   runAsUser: 1001
          envFrom:
          - configMapRef:
              name: core-env
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: core-ap.postgres.credentials.postgresql.acid.zalan.do
                  key: password
      imagePullSecrets:
      - name: regcred
          