apiVersion: v1
kind: Service
metadata:
  name: ccp-root-config
  namespace: {{ .Values.installation.name }}
spec:
  selector:
    component: ccp-root-config
  type: ClusterIP
  ports:
   - port: 80
     targetPort: 80