apiVersion: v1
kind: Service
metadata:
  name: activity-sneakers
  namespace: {{ .Values.installation.name }}
  labels:
    component: activity-sneakers
spec:
  selector:
    component: activity-sneakers
  type: ClusterIP
  ports:
   - port: 80
     targetPort: 80