apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: {{ .Values.installation.name }}
spec:
  selector:
    component: nginx
  type: LoadBalancer
  ports:
   - port: 80
     targetPort: 80