apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: {{ .Values.installation.name }}
  labels: 
    component: nginx
spec:
  selector:
    matchLabels:
      component: nginx
  template:
    metadata:
      labels:
        component: nginx
    spec:
      containers:
        - name: web-app
          image: frelaxy/web:latest
          ports:
          - containerPort: 80
          resources:
            requests:
              memory: 64Mi
              cpu: 20m
            limits:
              memory: 64Mi