apiVersion: batch/v1
kind: Job
metadata:
  name: db-seed-job
  namespace: {{ .Values.installation.name }}
  labels:
    job: seed
spec:
#  ttlSecondsAfterFinished: 10
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: seed
          image: {{ .Values.image.registry }}/{{ .Values.image.repository.core }}:{{ .Values.image.tag }}
          command: ['bin/rails']
          args: ['db:seed']
          volumeMounts:
          - name: seeds-pvc
            mountPath: /app/db/seeds
          ports:
          - containerPort: 80
          envFrom:
          - configMapRef:
              name: core-env
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: core-ap.postgres.credentials.postgresql.acid.zalan.do
                  key: password
      imagePullSecrets:
      - name: regcred
      volumes:
        - name: seeds-pvc
          persistentVolumeClaim:
            claimName: seeds-pvc