apiVersion: v1
kind: PersistentVolume
metadata:
  name: seeds-pv
  namespace: {{ .Values.installation.name }}
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: rails-seeds
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/seeds"
