# apiVersion: rabbitmq.com/v1beta1
# kind: RabbitmqCluster
# metadata:
#   name: rabbit
# spec:
#   replicas: 1
#   resources:
#     requests:
#       cpu: 50m
#       memory: 256Mi
#     limits:
#       cpu: 50m
#       memory: 256Mi
#   affinity:
#     podAntiAffinity:
#       preferredDuringSchedulingIgnoredDuringExecution:
#       - weight: 100
#         podAffinityTerm:
#           labelSelector:
#             matchExpressions:
#               - key: app.kubernetes.io/name
#                 operator: In
#                 values:
#                 - pod-anti-affinity
#           topologyKey: kubernetes.io/hostname