apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Values.installation.name }}
spec:
  selector:
    component: redis
  type: ClusterIP
  ports:
   - port: 6379
     targetPort: 6379